import { CustomerData } from "./type";

export const FAKE_CUSTOMER_DATA: CustomerData[] = [
  {
    customerName: "台北 永豐商行",
    contactPerson: "林志明",
    landlinePhone: "02-2345-6789",
    mobilePhone: "0912-345-678",
    address: "台北市中正區重慶南路一段100號",
  },
  {
    customerName: "高雄 富貴超市",
    contactPerson: "陳美玲",
    landlinePhone: "07-1234-5678",
    mobilePhone: "",
    address: "高雄市前鎮區中華五路200號",
  },
  {
    customerName: "台中 信義百貨",
    contactPerson: "王大明",
    landlinePhone: "",
    mobilePhone: "0923-456-789",
    address: "",
  },
  {
    customerName: "台南 建國食品行",
    contactPerson: "李淑芬",
    landlinePhone: "06-2345-6789",
    mobilePhone: "0934-567-890",
    address: "台南市中西區民族路三段88號",
  },
  {
    customerName: "桃園 中山商店",
    contactPerson: "張偉豪",
    landlinePhone: "03-3456-7890",
    mobilePhone: "",
    address: "桃園市桃園區中正路150號",
  },
  {
    customerName: "新竹 光復雜貨店",
    contactPerson: "劉佳穎",
    landlinePhone: "",
    mobilePhone: "0945-678-901",
    address: "",
  },
  {
    customerName: "新北 三重便利商店",
    contactPerson: "黃建國",
    landlinePhone: "02-8912-3456",
    mobilePhone: "0956-789-012",
    address: "新北市三重區重新路五段300號",
  },
  {
    customerName: "基隆 仁愛百貨",
    contactPerson: "吳佩珊",
    landlinePhone: "02-2456-7890",
    mobilePhone: "",
    address: "基隆市仁愛區孝一路120號",
  },
  {
    customerName: "嘉義 和平商行",
    contactPerson: "鄭俊傑",
    landlinePhone: "",
    mobilePhone: "0967-890-123",
    address: "",
  },
  {
    customerName: "彰化 民生食品店",
    contactPerson: "謝雅婷",
    landlinePhone: "04-7234-5678",
    mobilePhone: "0978-901-234",
    address: "彰化市中山路二段220號",
  },
  {
    customerName: "屏東 勝利超市",
    contactPerson: "蔡文傑",
    landlinePhone: "08-7345-6789",
    mobilePhone: "",
    address: "屏東市民生路150號",
  },
  {
    customerName: "宜蘭 東港商店",
    contactPerson: "楊淑華",
    landlinePhone: "",
    mobilePhone: "0989-012-345",
    address: "",
  },
  {
    customerName: "花蓮 中華雜貨行",
    contactPerson: "賴志豪",
    landlinePhone: "03-8234-5678",
    mobilePhone: "0921-123-456",
    address: "花蓮市中華路300號",
  },
  {
    customerName: "台東 成功百貨",
    contactPerson: "周美珍",
    landlinePhone: "089-345-678",
    mobilePhone: "",
    address: "台東市中正路180號",
  },
  {
    customerName: "苗栗 文化超商",
    contactPerson: "胡建成",
    landlinePhone: "",
    mobilePhone: "0932-234-567",
    address: "",
  },
  {
    customerName: "南投 日月商行",
    contactPerson: "馬詩涵",
    landlinePhone: "049-2234-567",
    mobilePhone: "0943-345-678",
    address: "南投市中興路250號",
  },
  {
    customerName: "雲林 虎尾食品店",
    contactPerson: "孫志強",
    landlinePhone: "05-6345-678",
    mobilePhone: "",
    address: "雲林縣虎尾鎮林森路一段100號",
  },
  {
    customerName: "澎湖 馬公百貨",
    contactPerson: "郭雅芳",
    landlinePhone: "",
    mobilePhone: "0954-456-789",
    address: "",
  },
  {
    customerName: "金門 金城商店",
    contactPerson: "羅建宏",
    landlinePhone: "082-323-456",
    mobilePhone: "0965-567-890",
    address: "金門縣金城鎮民族路90號",
  },
  {
    customerName: "連江 南竿超市",
    contactPerson: "蕭佩君",
    landlinePhone: "0836-234-567",
    mobilePhone: "",
    address: "連江縣南竿鄉福沃村120號",
  },
  {
    customerName: "台北 大安雜貨行",
    contactPerson: "何俊毅",
    landlinePhone: "",
    mobilePhone: "0976-678-901",
    address: "",
  },
  {
    customerName: "台中 西屯便利店",
    contactPerson: "范曉萱",
    landlinePhone: "04-2456-7890",
    mobilePhone: "0987-789-012",
    address: "台中市西屯區台灣大道三段500號",
  },
  {
    customerName: "高雄 左營食品商行",
    contactPerson: "余文彬",
    landlinePhone: "07-5567-8901",
    mobilePhone: "",
    address: "高雄市左營區博愛二路380號",
  },
  {
    customerName: "台南 安平百貨店",
    contactPerson: "侯雅文",
    landlinePhone: "",
    mobilePhone: "0912-890-123",
    address: "",
  },
  {
    customerName: "新北 板橋超商",
    contactPerson: "鍾建華",
    landlinePhone: "02-2678-9012",
    mobilePhone: "0923-901-234",
    address: "新北市板橋區文化路一段200號",
  },
  {
    customerName: "桃園 中壢商行",
    contactPerson: "施佩雯",
    landlinePhone: "03-4567-8901",
    mobilePhone: "",
    address: "桃園市中壢區中北路280號",
  },
  {
    customerName: "台北 松山食材店",
    contactPerson: "曾志偉",
    landlinePhone: "",
    mobilePhone: "0934-012-345",
    address: "",
  },
  {
    customerName: "新竹 竹北百貨",
    contactPerson: "湯雅惠",
    landlinePhone: "03-5678-9012",
    mobilePhone: "0945-123-456",
    address: "新竹縣竹北市光明六路150號",
  },
  {
    customerName: "台中 北屯超市",
    contactPerson: "顏俊宇",
    landlinePhone: "04-2234-5678",
    mobilePhone: "",
    address: "台中市北屯區崇德路二段420號",
  },
  {
    customerName: "彰化 員林商店",
    contactPerson: "凌美玲",
    landlinePhone: "",
    mobilePhone: "0956-234-567",
    address: "",
  },
  {
    customerName: "高雄 鳳山雜貨行",
    contactPerson: "龔志銘",
    landlinePhone: "07-7456-7890",
    mobilePhone: "0967-345-678",
    address: "高雄市鳳山區中山路320號",
  },
  {
    customerName: "嘉義 太保食品店",
    contactPerson: "戴淑芬",
    landlinePhone: "05-2345-678",
    mobilePhone: "",
    address: "嘉義縣太保市祥和一路88號",
  },
  {
    customerName: "台南 永康百貨",
    contactPerson: "程建國",
    landlinePhone: "",
    mobilePhone: "0978-456-789",
    address: "",
  },
  {
    customerName: "屏東 潮州商行",
    contactPerson: "武雅婷",
    landlinePhone: "08-7789-0123",
    mobilePhone: "0989-567-890",
    address: "屏東縣潮州鎮中山路180號",
  },
  {
    customerName: "宜蘭 羅東超市",
    contactPerson: "錢志豪",
    landlinePhone: "03-9567-8901",
    mobilePhone: "",
    address: "宜蘭縣羅東鎮公正路250號",
  },
  {
    customerName: "苗栗 竹南便利店",
    contactPerson: "石佩珊",
    landlinePhone: "",
    mobilePhone: "0921-678-901",
    address: "",
  },
  {
    customerName: "南投 草屯雜貨行",
    contactPerson: "莊俊傑",
    landlinePhone: "049-2345-678",
    mobilePhone: "0932-789-012",
    address: "南投縣草屯鎮中正路360號",
  },
  {
    customerName: "雲林 斗六食品店",
    contactPerson: "竺雅婷",
    landlinePhone: "05-5345-678",
    mobilePhone: "",
    address: "雲林縣斗六市文化路200號",
  },
  {
    customerName: "花蓮 吉安百貨",
    contactPerson: "游文傑",
    landlinePhone: "",
    mobilePhone: "0943-890-123",
    address: "",
  },
  {
    customerName: "台東 關山商店",
    contactPerson: "詹淑華",
    landlinePhone: "089-811-234",
    mobilePhone: "0954-901-234",
    address: "台東縣關山鎮中華路90號",
  },
  {
    customerName: "基隆 安樂超商",
    contactPerson: "尤建成",
    landlinePhone: "02-2431-2345",
    mobilePhone: "",
    address: "基隆市安樂區安樂路二段150號",
  },
  {
    customerName: "台北 萬華雜貨行",
    contactPerson: "岳詩涵",
    landlinePhone: "",
    mobilePhone: "0965-012-345",
    address: "",
  },
  {
    customerName: "新北 新店百貨",
    contactPerson: "樊志強",
    landlinePhone: "02-2218-2345",
    mobilePhone: "0976-123-456",
    address: "新北市新店區北新路三段280號",
  },
  {
    customerName: "桃園 龜山食品店",
    contactPerson: "衛雅芳",
    landlinePhone: "03-3298-765",
    mobilePhone: "",
    address: "桃園市龜山區文化一路200號",
  },
  {
    customerName: "台中 南屯商行",
    contactPerson: "雷建宏",
    landlinePhone: "",
    mobilePhone: "0987-234-567",
    address: "",
  },
  {
    customerName: "高雄 三民超市",
    contactPerson: "童佩君",
    landlinePhone: "07-3801-234",
    mobilePhone: "0912-345-678",
    address: "高雄市三民區建國三路450號",
  },
  {
    customerName: "台南 仁德便利店",
    contactPerson: "包俊毅",
    landlinePhone: "06-2701-234",
    mobilePhone: "",
    address: "台南市仁德區中山路320號",
  },
  {
    customerName: "新竹 香山雜貨行",
    contactPerson: "葉曉萱",
    landlinePhone: "",
    mobilePhone: "0923-456-789",
    address: "",
  },
  {
    customerName: "彰化 和美百貨",
    contactPerson: "牛文彬",
    landlinePhone: "04-7351-234",
    mobilePhone: "0934-567-890",
    address: "彰化縣和美鎮彰美路五段160號",
  },
  {
    customerName: "嘉義 民雄食品店",
    contactPerson: "卓雅文",
    landlinePhone: "05-2061-234",
    mobilePhone: "",
    address: "嘉義縣民雄鄉中樂路80號",
  },
];
