import { PriceData } from "./type";

export const FAKE_PRICE_DATA: PriceData[] = [
  {
    customerName: "高雄 永豐行",
    productName: "特級米 10公斤裝",
    unit: "包",
    costPerUnit: 350,
    pricePerUnit: 450,
    lastOutboundDate: "2025-10-05",
  },
  {
    customerName: "台北 信義商行",
    productName: "醬油膏 5入/箱",
    unit: "箱",
    costPerUnit: 280,
    pricePerUnit: 380,
    lastOutboundDate: "2025-10-03",
  },
  {
    customerName: "台中 建國百貨",
    productName: "洗髮精 12入/組",
    unit: "組",
    costPerUnit: 420,
    pricePerUnit: 550,
    lastOutboundDate: "2025-10-07",
  },
  {
    customerName: "台南 中正行",
    productName: "衛生紙 8入/提",
    unit: "提",
    costPerUnit: 180,
    pricePerUnit: 250,
    lastOutboundDate: "2025-10-01",
  },
  {
    customerName: "桃園 大同商行",
    productName: "沙拉油 6瓶/箱",
    unit: "箱",
    costPerUnit: 520,
    pricePerUnit: 680,
    lastOutboundDate: "2025-10-04",
  },
  {
    customerName: "新北 文化行",
    productName: "麵條 20包/箱",
    unit: "箱",
    costPerUnit: 380,
    pricePerUnit: 500,
    lastOutboundDate: "2025-10-06",
  },
  {
    customerName: "台中 復興百貨",
    productName: "餅乾 24入/盒",
    unit: "盒",
    costPerUnit: 290,
    pricePerUnit: 390,
    lastOutboundDate: "2025-10-02",
  },
  {
    customerName: "高雄 三民行",
    productName: "礦泉水 24瓶/箱",
    unit: "箱",
    costPerUnit: 160,
    pricePerUnit: 220,
    lastOutboundDate: "2025-10-08",
  },
  {
    customerName: "台北 南港商行",
    productName: "洗衣粉 15入/箱",
    unit: "箱",
    costPerUnit: 450,
    pricePerUnit: 600,
    lastOutboundDate: "2025-10-05",
  },
  {
    customerName: "新竹 東門行",
    productName: "泡麵 30包/箱",
    unit: "箱",
    costPerUnit: 340,
    pricePerUnit: 450,
    lastOutboundDate: "2025-10-03",
  },
  {
    customerName: "台南 永康商行",
    productName: "飲料罐 24入/箱",
    unit: "箱",
    costPerUnit: 280,
    pricePerUnit: 380,
    lastOutboundDate: "2025-10-09",
  },
  {
    customerName: "基隆 仁愛行",
    productName: "洗碗精 10瓶/組",
    unit: "組",
    costPerUnit: 220,
    pricePerUnit: 300,
    lastOutboundDate: "2025-10-01",
  },
  {
    customerName: "高雄 鳳山百貨",
    productName: "牙膏 16入/箱",
    unit: "箱",
    costPerUnit: 380,
    pricePerUnit: 500,
    lastOutboundDate: "2025-10-07",
  },
  {
    customerName: "台北 松山行",
    productName: "咖啡包 50入/盒",
    unit: "盒",
    costPerUnit: 420,
    pricePerUnit: 560,
    lastOutboundDate: "2025-10-04",
  },
  {
    customerName: "嘉義 中山商行",
    productName: "濕紙巾 12包/提",
    unit: "提",
    costPerUnit: 180,
    pricePerUnit: 250,
    lastOutboundDate: "2025-10-06",
  },
  {
    customerName: "屏東 潮州行",
    productName: "罐頭 20罐/箱",
    unit: "箱",
    costPerUnit: 560,
    pricePerUnit: 720,
    lastOutboundDate: "2025-10-02",
  },
  {
    customerName: "桃園 中壢商行",
    productName: "茶葉 8入/盒",
    unit: "盒",
    costPerUnit: 640,
    pricePerUnit: 850,
    lastOutboundDate: "2025-10-08",
  },
  {
    customerName: "台中 西屯百貨",
    productName: "牙刷 30支/盒",
    unit: "盒",
    costPerUnit: 320,
    pricePerUnit: 450,
    lastOutboundDate: "2025-10-05",
  },
  {
    customerName: "新北 板橋行",
    productName: "肥皂 24入/箱",
    unit: "箱",
    costPerUnit: 280,
    pricePerUnit: 380,
    lastOutboundDate: "2025-10-03",
  },
  {
    customerName: "台南 安平商行",
    productName: "麥片 12盒/組",
    unit: "組",
    costPerUnit: 480,
    pricePerUnit: 650,
    lastOutboundDate: "2025-10-09",
  },
  {
    customerName: "花蓮 中華行",
    productName: "餅乾棒 36包/箱",
    unit: "箱",
    costPerUnit: 420,
    pricePerUnit: 560,
    lastOutboundDate: "2025-10-01",
  },
  {
    customerName: "宜蘭 羅東百貨",
    productName: "糖果 48包/盒",
    unit: "盒",
    costPerUnit: 360,
    pricePerUnit: 480,
    lastOutboundDate: "2025-10-07",
  },
  {
    customerName: "苗栗 竹南行",
    productName: "巧克力 20條/盒",
    unit: "盒",
    costPerUnit: 520,
    pricePerUnit: 700,
    lastOutboundDate: "2025-10-04",
  },
  {
    customerName: "彰化 員林商行",
    productName: "口香糖 60片/盒",
    unit: "盒",
    costPerUnit: 280,
    pricePerUnit: 380,
    lastOutboundDate: "2025-10-06",
  },
  {
    customerName: "台北 大安行",
    productName: "果汁 18瓶/箱",
    unit: "箱",
    costPerUnit: 440,
    pricePerUnit: 590,
    lastOutboundDate: "2025-10-02",
  },
  {
    customerName: "雲林 斗六百貨",
    productName: "餅乾 15包/袋",
    unit: "袋",
    costPerUnit: 240,
    pricePerUnit: 330,
    lastOutboundDate: "2025-10-08",
  },
  {
    customerName: "南投 草屯行",
    productName: "茶包 100入/盒",
    unit: "盒",
    costPerUnit: 380,
    pricePerUnit: 520,
    lastOutboundDate: "2025-10-05",
  },
  {
    customerName: "台東 關山商行",
    productName: "蜜餞 10包/組",
    unit: "組",
    costPerUnit: 320,
    pricePerUnit: 450,
    lastOutboundDate: "2025-10-03",
  },
  {
    customerName: "高雄 左營行",
    productName: "洗手乳 8瓶/組",
    unit: "組",
    costPerUnit: 280,
    pricePerUnit: 380,
    lastOutboundDate: "2025-10-09",
  },
  {
    customerName: "新竹 竹北百貨",
    productName: "衛生棉 24包/箱",
    unit: "箱",
    costPerUnit: 560,
    pricePerUnit: 750,
    lastOutboundDate: "2025-10-01",
  },
  {
    customerName: "台中 豐原行",
    productName: "棉花棒 20盒/組",
    unit: "組",
    costPerUnit: 220,
    pricePerUnit: 300,
    lastOutboundDate: "2025-10-07",
  },
  {
    customerName: "桃園 龍潭商行",
    productName: "面膜 10片/盒",
    unit: "盒",
    costPerUnit: 180,
    pricePerUnit: 250,
    lastOutboundDate: "2025-10-04",
  },
  {
    customerName: "台北 內湖行",
    productName: "漱口水 6瓶/組",
    unit: "組",
    costPerUnit: 420,
    pricePerUnit: 560,
    lastOutboundDate: "2025-10-06",
  },
  {
    customerName: "新北 三重百貨",
    productName: "沐浴乳 12瓶/箱",
    unit: "箱",
    costPerUnit: 520,
    pricePerUnit: 700,
    lastOutboundDate: "2025-10-02",
  },
  {
    customerName: "台南 新營行",
    productName: "洗面乳 15支/組",
    unit: "組",
    costPerUnit: 360,
    pricePerUnit: 490,
    lastOutboundDate: "2025-10-08",
  },
  {
    customerName: "高雄 小港商行",
    productName: "洗髮精 6瓶/組",
    unit: "組",
    costPerUnit: 380,
    pricePerUnit: 520,
    lastOutboundDate: "2025-10-05",
  },
  {
    customerName: "嘉義 朴子行",
    productName: "牙線棒 30盒/箱",
    unit: "箱",
    costPerUnit: 420,
    pricePerUnit: 580,
    lastOutboundDate: "2025-10-03",
  },
  {
    customerName: "基隆 中山百貨",
    productName: "刮鬍刀 24支/盒",
    unit: "盒",
    costPerUnit: 320,
    pricePerUnit: 450,
    lastOutboundDate: "2025-10-09",
  },
  {
    customerName: "屏東 東港行",
    productName: "洗衣精 8瓶/箱",
    unit: "箱",
    costPerUnit: 560,
    pricePerUnit: 750,
    lastOutboundDate: "2025-10-01",
  },
  {
    customerName: "台中 沙鹿商行",
    productName: "柔軟精 10瓶/組",
    unit: "組",
    costPerUnit: 380,
    pricePerUnit: 520,
    lastOutboundDate: "2025-10-07",
  },
  {
    customerName: "桃園 八德行",
    productName: "垃圾袋 20捲/箱",
    unit: "箱",
    costPerUnit: 280,
    pricePerUnit: 380,
    lastOutboundDate: "2025-10-04",
  },
  {
    customerName: "台北 中山百貨",
    productName: "保鮮膜 12捲/組",
    unit: "組",
    costPerUnit: 240,
    pricePerUnit: 330,
    lastOutboundDate: "2025-10-06",
  },
  {
    customerName: "新北 新莊行",
    productName: "鋁箔紙 15捲/箱",
    unit: "箱",
    costPerUnit: 320,
    pricePerUnit: 440,
    lastOutboundDate: "2025-10-02",
  },
  {
    customerName: "台南 仁德商行",
    productName: "洗碗海綿 40個/袋",
    unit: "袋",
    costPerUnit: 180,
    pricePerUnit: 250,
    lastOutboundDate: "2025-10-08",
  },
  {
    customerName: "高雄 楠梓行",
    productName: "抹布 30條/包",
    unit: "包",
    costPerUnit: 220,
    pricePerUnit: 300,
    lastOutboundDate: "2025-10-05",
  },
  {
    customerName: "彰化 鹿港百貨",
    productName: "除濕劑 8入/組",
    unit: "組",
    costPerUnit: 280,
    pricePerUnit: 390,
    lastOutboundDate: "2025-10-03",
  },
  {
    customerName: "宜蘭 礁溪行",
    productName: "香氛蠟燭 12個/盒",
    unit: "盒",
    costPerUnit: 420,
    pricePerUnit: 580,
    lastOutboundDate: "2025-10-09",
  },
  {
    customerName: "苗栗 頭份商行",
    productName: "芳香劑 24瓶/箱",
    unit: "箱",
    costPerUnit: 360,
    pricePerUnit: 490,
    lastOutboundDate: "2025-10-01",
  },
  {
    customerName: "台中 大里行",
    productName: "蚊香 20盒/組",
    unit: "組",
    costPerUnit: 280,
    pricePerUnit: 380,
    lastOutboundDate: "2025-10-07",
  },
  {
    customerName: "新竹 湖口百貨",
    productName: "殺蟲劑 16瓶/箱",
    unit: "箱",
    costPerUnit: 520,
    pricePerUnit: 700,
    lastOutboundDate: "2025-10-04",
  },
];
